### ISSUE TITLE
Promise Rejection Error

### ISSUE THREAD

**Issue by dmastag** [jeduan/playup#24]
I keep getting this error when using this package in javascript
Could it be because I am using Node v8.2.1 and npm 5.3.0 ?

```
(node:27400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
(node:27400) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by dmastag** [comment]
Got more information after I put a catch on the upload function

```
D:\projectX>node upload.js
Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Sign.sign (crypto.js:329:26)
    at Object.sign (D:\projectX\node_modules\jwa\index.js:53:47)
    at Object.jwsSign [as sign] (D:\projectX\node_modules\jws\lib\sign-stream.js:23:26)
    at GoogleToken._signJWT (D:\projectX\node_modules\gtoken\lib\index.js:240:25)
    at GoogleToken._requestToken (D:\projectX\node_modules\gtoken\lib\index.js:195:15)
    at GoogleToken.getToken (D:\projectX\node_modules\gtoken\lib\index.js:77:19)
    at D:\projectX\node_modules\google-auth-library\lib\auth\jwtclient.js:137:21
    at JWT._createGToken (D:\projectX\node_modules\google-auth-library\lib\auth\jwtclient.js:226:12)
    at JWT.refreshToken_ (D:\projectX\node_modules\google-auth-library\lib\auth\jwtclient.js:133:15)
    at JWT.authorize (D:\projectX\node_modules\google-auth-library\lib\auth\jwtclient.js:112:8)
```

**Comment by dmastag** [comment]
Ok, found the problem
I should have put the private_key obtained **inside** the json file from the service account instead to a link to the json file in there

That should have been self explanatory, not sure why I didn't get that
