### ISSUE TITLE
Getting the client_email missing error 

### ISSUE THREAD

**Issue by kevalpatel2106** [jeduan/playup#29]
When I try to upload my app using the cli using following command
`playup --auth /client_secret.json /app-release.apk`

I get error like below: 
```
assert.js:41
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: Missing required parameter client_email
    at new Publisher (/usr/local/lib/node_modules/playup/lib/index.js:27:27)
    at Publisher (/usr/local/lib/node_modules/playup/lib/index.js:25:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/playup/cli.js:44:33)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
```

As I provided the auth.json file generated from the console, I think client_email is not required. Please correct me if I am wrong.

**Comment by nprail** [comment]
@kevalpatel2106 `client_email` should be in your `client_secret.json` file.
