### ISSUE TITLE
RangeError: Index out of range error

### ISSUE THREAD

**Issue by kevalpatel2106** [jeduan/playup#30]
I am getting below error while uploading the apk.

```
RangeError: Index out of range
 at checkOffset (buffer.js:968:11)
 at Buffer.readUInt16LE (buffer.js:1014:5)
 at BinaryXmlParser.readU16 (/home/travis/.nvm/versions/node/v8.7.0/lib/node_modules/playup/node_modules/node-apk-
```

**Comment by dmastag** [comment]
I got the same issue, did you manage to get this fixed @kevalpatel2106 ?

**Comment by kevalpatel2106** [comment]
@dmastag Nope.

**Comment by dmastag** [comment]
I found out that this issue for me happened when I was using cordova 6.4.0
So I had to downgrade to 6.3.0 and its now working again

Hope that helps of you are using cordova also

**Comment by Makatumba** [comment]
we fixed this issue by replacing node-apk-parser with adbkit-apkreader in our fork

**Comment by dmastag** [comment]
@Makatumba  Am gonna keep an eye on the Merge Request, hope you can check why the tests are failing so it will be merged

**Comment by vsmori** [comment]
+1

**Comment by vsmori** [comment]
@Makatumba , is your fork public?

**Comment by Makatumba** [comment]
@vsmori, yes it ist. 
this is the link to other repo:
https://github.com/smartcrm/playup

**Comment by vsmori** [comment]
@Makatumba , thank you man!!!
