### ISSUE TITLE
How do I upload .aab (Android App bundle) file

### ISSUE THREAD

**Issue by dmastag** [jeduan/playup#39]
I recently changed my builds to generate .aab files since Google Play kept complaining to change into that.

But unfortunately I can't seem to use playup to upload .aab files with the following error

```
Error: APK does not contain 'AndroidManifest.xml'
    at ApkReader.readManifestSync (/usr/local/lib/node_modules/playup/node_modules/node-apk-parser/lib/apkreader.js:39:15)
    at /usr/local/lib/node_modules/playup/lib/upload.js:86:31
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

**Comment by nprail** [comment]
Playup isn't maintained anymore. However, I created a fork, [apkup](https://github.com/eventOneHQ/apkup), that is maintained. I'm planning on adding .aab support soon here. PRs are welcome too.

See [eventOneHQ/apkup#4](https://github.com/eventOneHQ/apkup/issues/4).

**Comment by nprail** [comment]
This functionality is now available on [apkup](https://github.com/eventOneHQ/apkup)!

See eventOneHQ/apkup#4.
